language: php

php:
    - '7.1'

env:
    - secure: hUaBzP2+qG2o4DB737wn17LlPWDT96IfxA6/aao/WMbXiI+PtiE8VBDJ6npaWVW124NXQtH7RpMtAFAO3RC9GpSiiE9HSnrwn6athf/7jr9lZ2gclr8oMXoQj8B9C0hTOwj8CQgBEoKZX59RZVZ4ENJis9NkHBA0f1aCbEXWQPV0tb9Zrb6wHgQOeFT1MUaf1itQp0NT5gByjF3IQ1vIgdDMW1lgQx5CDQ5Dk4aDlQqtARlpXMLrhN3ODWr+NR7apeplgtOjKEt1UmgXwaymyFrwmpENS2yxfzgHIdfxjPVRD/62obUcU/z3+EeohdTMBiOvyvqsk18UoFPD7HDsEifgjTAodzu4rYsFvQTEgXyg0Taf4gzSj241ONXKRgHhBglaFujxAVAtgwIe5BWHvIa3FCZQYhfy9V0HNrF/fd2Ob+XlM5IPtznyL7xAk2sur2uJ2kbmFJMKdvpDaXVjZU5f98DJvEaau4rPc2udArrg1vYvDVThpdsKr6ZdUPcs0p8lQPsOkG4zGA8Hw8oOpVMI0+eLcnU33tbvYn20LbeH3l07QzTljDOsC0wwXb0AWmAOn7QgcMWYeticN81Iz6W8jgIRtE8uBIV02Qdd1P4KjDCfxceQxVzKY30BTAUBy1FoUL6vCtmzZs2DuP1kXXu3iJgzocUvJeFLIO5RWPE=

cache:
    directories:
        - "$HOME/.npm"
        - "$HOME/.composer/cache"

before_install:
    - phpenv config-rm xdebug.ini
    - nvm install 8
    - nvm use 8

install:
    - npm install
    - npm run composer:install

script:
    - npm run compile
    - npx vsce package -o "tenkawa-php.vsix"
    - if [ "$TRAVIS_PULL_REQUEST" = false -a -n "$TRAVIS_TAG" ]; then npx vsce publish --pat "$VSTS_TOKEN" --packagePath "tenkawa-php.vsix"; fi

deploy:
    provider: releases
    api_key:
        secure: OPocpvACxKEqqUbTwmVTWWzovgXpbE7UUD/K+I3Kbfq4kBHoZR1brJvBJAjZavW5d8w71fk5ZxlXlAQQB96tXU8ag4W+61q0U2MvQYi0FGWlmw+0K4M2cNVLk7zgPOe7KUtZDiQmfM6v5d+ASdZABjOC+59vAB5o/KzJUIWQCF+8l2GUw2krMIqISZtKPsPr2d4SipSraVs22cvVPv05DuRJdUghPT1Vc0AjGg6kQ1DrTg+8ifXZX5K/xYrXVHvCSyhTszx+4beSZ72vRcxPpiLlNUbe/PEEjr2owjQcDZ2jG+rdu1abuDWRb2fjpGZL5fIRqiWltJ72aoKZf55CrQ2EbxuPXjCJDZPh7m4zr5e7j1V/Lq5tGlYtofwaaciCRlG5gUfYei0qmin6BVcXQGHkhfIM1BtP1RaZcL0z5mGSD1K8ckU4nXS4sDTvnDUzp2ZmI+C23yX0GHxuQ6E5SiTjkd1ESMVX006TgS7dpLRqzSSNhMWG2KuxRhyOEO3Bu7tzTKlhooqjCEar6pU0V3VlTZuIs71Fk8ZnUbZtsby2ARq+oroV/PlkKltCvrx/NUyA8g+35eQT7Qv+MyvBLH8JulusUyWRbYWrgQaEM+sb94ZYw4SgoltO/M8CDt8QEcSCtUqq1RTHRkna2dE5z0yRuTXi5dix1VUPBZlAv/8=
    file: "tenkawa-php.vsix"
    skip_cleanup: true
    on:
        tags: true
